version: 2
archives:
  - format_overrides:
    - goos: windows
      format: zip
before:
  hooks:
    - go mod download
brews:
  - dependencies:
    - go
    description: Terraform Provider Documentation Tool
    directory: Formula
    repository:
      owner: bflad
      name: homebrew-tap
    homepage: https://github.com/bflad/tfproviderdocs
    install: |
      bin.install "tfproviderdocs"
    test: |
      system "#{bin}/tfproviderdocs -v"
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - darwin
    - windows
    - linux
    goarch:
    - amd64
    - arm64
    - 386
    ldflags:
    - -s -w -X github.com/bflad/tfproviderdocs/version.Version={{.Version}} -X github.com/bflad/tfproviderdocs/version.VersionPrerelease=
    main: .
changelog:
  disable: true
dockers:
  - build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"
    image_templates:
    - 'bflad/tfproviderdocs:{{ .Version }}'
    - 'bflad/tfproviderdocs:{{ .Major }}.{{ .Minor }}'
    - 'bflad/tfproviderdocs:latest'
milestones:
  - close: true
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
